# Site settings
title: Jekyll Theme Stellar
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by HTML5 Up,<br>
  ported to Jekyll by MOODULE<br>
  and released under the Creative Commons.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px:
  url: https://github.com/moodule
facebook:
  url: https://github.com/moodule
github:
  url: https://github.com/moodule
gitlab:
  url: https://github.com/moodule
instagram:
  url: https://github.com/moodule
linkedin:
  url: https://github.com/moodule
medium:
  url: https://github.com/moodule
pinterest:
  url: https://github.com/moodule
slack:
  url: https://github.com/moodule
snapchat:
  url: https://github.com/moodule
twitter:
  url: https://github.com/moodule

# Optional elements
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github

# Recaptcha in forms
recaptcha:
  sitekey: 6LdbdsgUAAAAAF0RwvZAEFVU_t1wZ3Jw_sOiZ2nz

# Collections
collections:
  home_sections:
    output: false
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moodule.github.io/jekyll-theme-stellar" # the base hostname & protocol for your site, e.g. http://example.com
author: David Mougeolle
copyright:
  holder: Untitled
  license: CC0

# Exclude from processing
